# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- task: DotNetCoreCLI@2
  displayName: 'My Build'
  inputs:
    command: 'build'
    projects: |
      ./PrimeService

- script: dotnet test '**/PrimeService.Tests/PrimeService.Tests.csproj' --configuration $(buildConfiguration) --collect "Code coverage"